/**
 * Frontend route definitions matching backend OpenAPI schema.
 * Maintained for contract validation against backend app.openapi().
 */
export const API_ROUTES = {
  health: '/api/health',
  databaseHealth: '/api/health/database',
  states: '/api/states',
  districts: '/api/districts',
  habitations: '/api/habitations',
  habitationDetail: '/api/habitations/{habitation_id}',
  habitationRisk: '/api/habitations/{habitation_id}/risk',
  habitationRiskExplanation: '/api/habitations/{habitation_id}/risk/explanation',
  habitationRelocation: '/api/habitations/{habitation_id}/relocation',
  habitationDiscoveryRuns: '/api/habitations/{habitation_id}/candidate-discovery-runs',
  redZones: '/api/red-zones',
  hazardZones: '/api/hazard-zones',
  hazardZonesGeojson: '/api/hazard-zones/geojson',
  candidateSites: '/api/candidate-sites',
  candidateSitesGeojson: '/api/candidate-sites/geojson',
  candidateParcels: '/api/candidate-parcels',
  candidateParcelsGeojson: '/api/candidate-parcels/geojson',
  candidateParcelDetail: '/api/candidate-parcels/{parcel_id}',
  infrastructure: '/api/infrastructure',
  dataSources: '/api/data-sources',
  dataSourcesFreshness: '/api/data-sources/freshness',
  evidenceLayers: '/api/data-sources/evidence-layers',
  disasterEvents: '/api/disaster-events',
  metricsSummary: '/api/metrics/summary',
  relocationPriorities: '/api/relocation-priorities',
  candidateDiscoveryRun: '/api/analysis/candidates/habitations/{habitation_id}',
  optimizationRun: '/api/optimization/run',
  optimizationRunDetail: '/api/optimization/runs/{run_id}',
  optimizationHabitationPlans: '/api/optimization/habitations/{habitation_id}/latest-plans',
  optimizationPlanDetail: '/api/optimization/plans/{plan_id}',
  digitalTwinSimulate: '/api/digital-twin/simulate',
  digitalTwinRobustness: '/api/digital-twin/plans/{plan_id}/robustness',
  governanceDemoSnapshotRaini: '/api/governance/demo-snapshot/raini',
  governanceDossier: '/api/governance/habitations/{habitation_id}/dossier',
  governanceDossierHtml: '/api/governance/habitations/{habitation_id}/dossier/html',
  governanceDataHonestyAudit: '/api/governance/data-honesty-audit',
  governanceObservations: '/api/governance/observations',
  governanceLandStatus: '/api/governance/land-status',
  governanceConsultations: '/api/governance/consultations',
  governanceReviews: '/api/governance/reviews',
  governanceOverrides: '/api/governance/overrides',
  governanceAuditLogs: '/api/governance/audit-logs',
} as const;
